// Post-build step: turn dist/ into an offline-capable static app.
// Writes dist/sw.js with a full precache manifest of every emitted file.
import { readdir, stat, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

const dist = new URL('../dist', import.meta.url).pathname

async function walk(dir, base = dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(p, base)))
    else out.push(relative(base, p).split('\\').join('/'))
  }
  return out
}

const files = (await walk(dist)).filter((f) => f !== 'sw.js' && !f.endsWith('.map'))
const version = Date.now()

const sw = `// DeutschPath service worker — generated by scripts/generate-sw.mjs
// Precaches every build asset so the game runs with zero network after first load.
const VERSION = 'deutschpath-${version}'
const PRECACHE = ${JSON.stringify(files, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(VERSION).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return
  // cache-first, then network; successful network responses refresh the cache
  event.respondWith(
    caches.match(req, { ignoreSearch: req.mode === 'navigate' }).then((hit) => {
      if (hit) {
        fetch(req).then((res) => {
          if (res && res.ok) caches.open(VERSION).then((c) => c.put(req, res.clone()))
        }).catch(() => {})
        return hit
      }
      return fetch(req).then((res) => {
        if (res && res.ok) caches.open(VERSION).then((c) => c.put(req, res.clone()))
        return res
      })
    }),
  )
})
`

await writeFile(join(dist, 'sw.js'), sw)
console.log(`sw.js generated with ${files.length} precached files`)
